on: 
  pull_request:
    
permissions:
  id-token: write 

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  deploy_backend:
      runs-on: ubuntu-latest
      needs: deploy_infrastructure
      environment: production

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Publish the app
        run: dotnet publish -c Release --property:PublishDir=publish # Publish the app to the publish folder of the API project
        working-directory: ./backend # specify where to find the solution file
        
  deploy_frontend:
      runs-on: ubuntu-latest
      needs: deploy_infrastructure
      environment: production

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the app
        run: npm install && npm run lint && npm run build
        working-directory: ./frontend    
